[package]
name = "jwt-simple"
version = "0.12.1"
description = "Easy to use, secure, non opinionated JWT (JSON Web Tokens) implementation for Rust."
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/jedisct1/rust-jwt-simple"
homepage = "https://github.com/jedisct1/rust-jwt-simple"
categories = ["wasm", "api-bindings", "web-programming", "cryptography"]
keywords = ["jwt", "jws", "authentication", "tokens", "json"]
readme = "README.md"

[features]
cwt = ["ciborium"]
rsa = ["dep:rsa"]

[dependencies]
anyhow = "1.0.75"
binstring = "0.1.1"
ciborium = { version = "0.2.1", optional = true }
coarsetime = "0.1.33"
ct-codecs = "1.1.1"
ed25519-compact = { version = "2.1", features = ["pem"] }
hmac = "0.12"
digest = "0.10"
sha-1 = { version = "0.10", features = ["oid"] }
sha2 = { version = "0.10", features = ["oid"] }
ecdsa = { version = "0.16", features = ["der"] }
k256 = { version = "0.13.2", features = ["ecdsa", "std", "pkcs8", "pem"] }
p256 = { version = "0.13.2", features = ["ecdsa", "std", "pkcs8", "pem"] }
p384 = { version = "0.13.0", features = ["ecdsa", "std", "pkcs8", "pem"] }
p521 = { version = "0.13.0", features = ["ecdsa", "std", "pkcs8", "pem"] }
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
zeroize = "1.7.0"
getrandom = { version = "0.2", features = ["js"] }
rsa = { version = "0.9", optional = true }
spki = "0.7"


[dev-dependencies]
benchmark-simple = "0.1.8"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
codegen-units = 1
incremental = false
panic = "abort"

[profile.bench]
codegen-units = 1
